name: Deploy Lambda API

on:
  push:
    branches:
      - master
    paths:
      - src/GoOrder.API/**

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: src/GoOrder.API

      - name: Build API
        run: dotnet build --configuration Release --no-restore
        working-directory: src/GoOrder.API

      - name: Package Lambda
        run: |
          dotnet publish -c Release -o ./package
          zip -r lambda.zip ./package/
        working-directory: src/GoOrder.API

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload ZIP to S3
        run: |
          aws s3 cp lambda.zip s3://goorder-lambda-bucket/lambda.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Lambda from S3
        run: |
          aws lambda update-function-code --function-name GoOrderLambda \
           --s3-bucket goorder-lambda-bucket \
           --s3-key lambda.zip
