name: Deploy Infrastructure

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - infra/**

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        id: plan

      - name: Terraform Apply
        if: success() && steps.plan.outcome == 'success'
        run: terraform apply -auto-approve
