name: Deploy User Service

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - src/UserService/**

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Some Params to SSM
        run: |
          aws ssm put-parameter --name "/goorder/user_pool_client_id" --value "${{secrets.USER_POOL_CLIENT_ID}}" --type "SecureString" --overwrite
          aws ssm put-parameter --name "/goorder/user_pool_client_secret" --value "${{secrets.USER_POOL_CLIENT_SECRET}}" --type "SecureString" --overwrite

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: src/UserService

      - name: Build API
        run: dotnet build --configuration Release --no-restore
        working-directory: src/UserService

      - name: Install Amazon Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools --version 5.0.0
        working-directory: src/UserService

      - name: Package Lambda with Amazon.Lambda.Tools
        run: dotnet lambda package --configuration Release --runtime linux-x86 --self-contained false --output-package user_lambda.zip
        working-directory: src/UserService

      - name: Upload ZIP to S3
        run: |
          aws s3 cp user_lambda.zip s3://goorder-lambda-bucket/user_lambda.zip
        working-directory: src/UserService
