name: Deploy Infrastructure

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["Deploy User Service"]
    types:
      - completed

  push:
    branches:
      - master
    paths:
      - infra/** # also trigger if files in infra change

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: infra
        continue-on-error: true # ensure workflow doesn't fail if no changes are detected

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra
