name: Inventory Lambdas CI/CD

on:
  workflow_dispatch:

  push:
    branches: [master]
    paths:
      - "src/inventory/**"

jobs:
  deploy_all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip and deploy all inventory lambdas
        run: |
          set -e
          for dir in src/inventory/*/ ; do
            lambda=$(basename "$dir")
            echo "Zipping and deploying $lambda..."

            zip -r "inventory-$lambda.zip" "$dir"

            aws lambda update-function-code \
              --function-name "inventory-$lambda" \
              --zip-file "fileb://inventory-$lambda.zip"

            echo "inventory-$lambda deployed"
          done
