name: Push Order Service Lambdas

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - src/OrderService/**

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/OrderService

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build API
        run: dotnet build --configuration Release --no-restore

      - name: Install Amazon Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools --version 5.0.0

      - name: Package Lambda with Amazon.Lambda.Tools
        run: dotnet lambda package --configuration Release --runtime linux-x86 --self-contained false --output-package order_lambda.zip

      - name: Upload ZIP to S3
        run: |
          aws s3 cp order_lambda.zip s3://goorder-lambda-bucket/order_lambda.zip
